markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Sid Shah
url: http://zachholman.co
description: A collection of personal notes for programming contests solutions
twitter: iamsidd
github: sidharthshah
gravatar_url: http://en.gravatar.com/iamsidd